"""
test_link_heartbeat.py — LinkHeartbeat round-trips through the generated python.

Needs gen/python on sys.path (generated by `make python`).
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "gen" / "python"))


def test_link_heartbeat_roundtrip():
    from openddil.link.v1 import link_heartbeat_pb2 as pb

    msg = pb.LinkHeartbeat(
        link_id="edge-x",
        traffic=pb.LINK_TRAFFIC_IDLE,
        bridge_lag=-1,
    )
    msg.emitted_at.GetCurrentTime()

    parsed = pb.LinkHeartbeat()
    parsed.ParseFromString(msg.SerializeToString())

    assert parsed.link_id == "edge-x"
    assert parsed.traffic == pb.LINK_TRAFFIC_IDLE
    assert parsed.bridge_lag == -1
    assert parsed.HasField("emitted_at")


def test_link_traffic_unspecified_is_zero():
    from openddil.link.v1 import link_heartbeat_pb2 as pb

    assert pb.LINK_TRAFFIC_UNSPECIFIED == 0
    assert pb.LinkHeartbeat().traffic == pb.LINK_TRAFFIC_UNSPECIFIED
