"""
test_condition.py — Condition claims on OperationalState / ElementRollup, and
the ontology file that orders them.

Needs gen/python on sys.path (generated by `make python`).
"""
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "gen" / "python"))

LEVEL_PREFIX = "CONDITION_LEVEL_"
SOURCE_PREFIX = "CONDITION_SOURCE_"


def _state():
    from openddil.telemetry.v1 import telemetry_pb2 as t

    st = t.OperationalState()
    st.condition.level = t.CONDITION_LEVEL_DEGRADED
    st.condition.moved_by.append(t.CONDITION_SOURCE_EMISSION)
    c = st.condition.claims.add()
    c.source = t.CONDITION_SOURCE_EMISSION
    c.level = t.CONDITION_LEVEL_DEGRADED
    c.detail = "2/4 beams"
    c.observed_at.FromSeconds(1_700_000_000)
    c = st.condition.claims.add()
    c.source = t.CONDITION_SOURCE_APPEARANCE_DAMAGE
    c.level = t.CONDITION_LEVEL_NOMINAL
    return st


def test_operational_state_condition_roundtrip():
    from openddil.telemetry.v1 import telemetry_pb2 as t

    assert not t.OperationalState().HasField("condition")
    st = _state()
    parsed = t.OperationalState()
    parsed.ParseFromString(st.SerializeToString())
    assert parsed.HasField("condition")
    assert parsed.condition.level == t.CONDITION_LEVEL_DEGRADED
    assert list(parsed.condition.moved_by) == [t.CONDITION_SOURCE_EMISSION]
    assert len(parsed.condition.claims) == 2
    assert parsed.condition.claims[0].detail == "2/4 beams"
    assert parsed.condition.claims[0].observed_at.seconds == 1_700_000_000
    assert parsed.condition.claims[1].level == t.CONDITION_LEVEL_NOMINAL


def test_element_rollup_condition_roundtrip():
    from openddil.logistics.v1 import windowed_telemetry_pb2 as pb

    src = _state()
    msg = pb.WindowedTelemetry(asset_id="a-1")
    msg.element_rollup.element_count = 4
    msg.element_rollup.condition.CopyFrom(src.condition)

    parsed = pb.WindowedTelemetry()
    parsed.ParseFromString(msg.SerializeToString())
    assert parsed.element_rollup.HasField("condition")
    assert parsed.element_rollup.condition == src.condition


def test_condition_json_shape():
    from google.protobuf import json_format
    from openddil.telemetry.v1 import telemetry_pb2 as t

    st = _state()
    d = json_format.MessageToDict(st, preserving_proto_field_name=True)
    cond = d["condition"]
    assert cond["level"] == "CONDITION_LEVEL_DEGRADED"
    assert cond["moved_by"] == ["CONDITION_SOURCE_EMISSION"]
    assert cond["claims"][0]["source"] == "CONDITION_SOURCE_EMISSION"
    assert cond["claims"][0]["observed_at"]
    back = json_format.ParseDict(d, t.OperationalState())
    assert back == st


def _ontology():
    return yaml.safe_load((ROOT / "ontology" / "dis_condition.yaml").read_text(encoding="utf-8"))


def _names(enum_desc, prefix):
    return {v.name[len(prefix):] for v in enum_desc.values if v.number != 0}


def test_dis_condition_yaml():
    from openddil.telemetry.v1 import telemetry_pb2 as t

    doc = _ontology()
    levels = _names(t.DESCRIPTOR.enum_types_by_name["ConditionLevel"], LEVEL_PREFIX)
    sources = _names(t.DESCRIPTOR.enum_types_by_name["ConditionSource"], SOURCE_PREFIX)
    assert len(levels) == 7 and len(sources) == 4

    assert len(doc["level_order"]) == len(set(doc["level_order"]))
    assert set(doc["level_order"]) == levels
    assert len(doc["source_order"]) == len(set(doc["source_order"]))
    assert set(doc["source_order"]) == sources

    for v in doc["appearance"]["damage"].values():
        assert v in doc["level_order"]
    for key in ("power_plant_off", "deactivated"):
        assert doc["appearance"][key] in doc["level_order"]

    assert isinstance(doc["emission"]["baselines"], dict)
