"""
test_windowed_telemetry_rollup.py — ElementRollup on WindowedTelemetry round-trips.

Needs gen/python on sys.path (generated by `make python`).
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "gen" / "python"))


def test_element_rollup_roundtrip():
    from openddil.logistics.v1 import windowed_telemetry_pb2 as pb

    msg = pb.WindowedTelemetry(asset_id="a-1")
    msg.element_rollup.profile_name = "profile-x"
    msg.element_rollup.element_count = 23000
    msg.element_rollup.critical_count = 12
    msg.element_rollup.degraded_count = 340
    msg.element_rollup.avg_temp_c = 41.5
    msg.element_rollup.avg_load_pct = 62.25
    msg.element_rollup.observed_at.GetCurrentTime()
    msg.element_rollup.core_temp_c = 0.0

    parsed = pb.WindowedTelemetry()
    parsed.ParseFromString(msg.SerializeToString())

    r = parsed.element_rollup
    assert parsed.HasField("element_rollup")
    assert r.profile_name == "profile-x"
    assert r.element_count == 23000
    assert r.critical_count == 12
    assert r.degraded_count == 340
    assert r.avg_temp_c == 41.5
    assert r.avg_load_pct == 62.25
    assert r.HasField("observed_at")
    assert r.HasField("core_temp_c") and r.core_temp_c == 0.0
    assert not r.HasField("uptime_hours")


def test_element_rollup_absent_by_default():
    from openddil.logistics.v1 import windowed_telemetry_pb2 as pb

    assert not pb.WindowedTelemetry(asset_id="a-1").HasField("element_rollup")
    assert not pb.ElementRollup().HasField("core_temp_c")
